# Ignore everything by default
**

# Root workspace files
!pyproject.toml
!uv.lock

# All pyproject.toml files for dependency resolution
!**/pyproject.toml
.venv/**

# Workspace and used shared libraries
!02-backend/logging
!02-backend/temporal_codec_service/**
!04-shared-services/temporal/**
