"""make_document_name_nullable

Revision ID: 831cd18f2d19
Revises: 9000d8aa34dc
Create Date: 2026-01-14 09:18:01.068241

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "831cd18f2d19"
down_revision: str | Sequence[str] | None = "9000d8aa34dc"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plausibility_note_occurrence",
        "document_name",
        existing_type=sa.VARCHAR(),
        nullable=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "plausibility_note_occurrence",
        "document_name",
        existing_type=sa.VARCHAR(),
        nullable=False,
    )
    # ### end Alembic commands ###
