"""Initial migration

Revision ID: 85bd27a6db27
Revises:
Create Date: 2024-12-16 12:00:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "85bd27a6db27"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "plausibility_note",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("project_id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column("fact_text", sa.Text(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plausibility_note_project_id"),
        "plausibility_note",
        ["project_id"],
        unique=False,
    )

    op.create_table(
        "plausibility_note_occurrence",
        sa.Column("id", postgresql.UUID(as_uuid=True), nullable=False),
        sa.Column(
            "plausibility_note_id", postgresql.UUID(as_uuid=True), nullable=False
        ),
        sa.Column("document_id", sa.String(), nullable=False),
        sa.Column("document_name", sa.String(), nullable=False),
        sa.Column("content_excerpt", sa.Text(), nullable=False),
        sa.Column("page_number", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["plausibility_note_id"], ["plausibility_note.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_plausibility_note_occurrence_plausibility_note_id"),
        "plausibility_note_occurrence",
        ["plausibility_note_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_plausibility_note_occurrence_plausibility_note_id"),
        table_name="plausibility_note_occurrence",
    )
    op.drop_table("plausibility_note_occurrence")
    op.drop_index(
        op.f("ix_plausibility_note_project_id"), table_name="plausibility_note"
    )
    op.drop_table("plausibility_note")
    # ### end Alembic commands ###
