apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-workflow
  namespace: spark-workflow
  labels:
    app.kubernetes.io/part-of: spark-workflow
spec:
  project: default
  source:
    repoURL: https://github.com/RobertinoSolanas/spark-workflow-main.git
    targetRevision: main
    path: deployment/charts/spark-workflow
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-workflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
