"""auto-generated migration

Revision ID: 022ff6275f8e
Revises: fb1ee44cfcb8
Create Date: 2025-12-16 12:46:50.670127

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "022ff6275f8e"
down_revision: str | Sequence[str] | None = "fb1ee44cfcb8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("document", "file_id", existing_type=sa.UUID(), nullable=True)
    op.create_unique_constraint(
        "uq_document_type_project_name", "document_type", ["project_id", "name"]
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_document_type_project_name", "document_type", type_="unique")
    op.alter_column("document", "file_id", existing_type=sa.UUID(), nullable=False)
    # ### end Alembic commands ###
