"""auto-generated migration

Revision ID: 090bbfca8fb1
Revises: 022ff6275f8e
Create Date: 2025-12-17 12:50:02.438005

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "090bbfca8fb1"
down_revision: str | Sequence[str] | None = "022ff6275f8e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("document_document_type_id_fkey"), "document", type_="foreignkey"
    )
    op.create_unique_constraint(
        "uq_document_type_id_project_id", "document_type", ["id", "project_id"]
    )
    op.create_foreign_key(
        None,
        "document",
        "document_type",
        ["document_type_id", "project_id"],
        ["id", "project_id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "document", type_="foreignkey")
    op.drop_constraint(
        "uq_document_type_id_project_id", "document_type", type_="unique"
    )
    op.create_foreign_key(
        op.f("document_document_type_id_fkey"),
        "document",
        "document_type",
        ["document_type_id"],
        ["id"],
        ondelete="CASCADE",
    )
    # ### end Alembic commands ###
