"""auto-generated migration

Revision ID: 2fb6d5cff5ba
Revises: f3b8af6e7451
Create Date: 2026-02-06 11:07:43.473929

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "2fb6d5cff5ba"
down_revision: str | Sequence[str] | None = "f3b8af6e7451"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id", "project_id", name="uq_category_id_project_id"),
        sa.UniqueConstraint("project_id", "name", name="uq_category_project_name"),
    )
    op.create_index(
        op.f("ix_category_project_id"), "category", ["project_id"], unique=False
    )
    op.create_table(
        "template_category",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_template_category_name"),
    )
    op.create_table(
        "template_document_type",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("template_category_id", sa.UUID(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("expected_count", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["template_category_id"], ["template_category.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="uq_template_document_type_name"),
    )
    op.create_index(
        op.f("ix_template_document_type_template_category_id"),
        "template_document_type",
        ["template_category_id"],
        unique=False,
    )
    op.add_column("document_type", sa.Column("category_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_document_type_category_id"),
        "document_type",
        ["category_id"],
        unique=False,
    )
    op.create_foreign_key(
        None,
        "document_type",
        "category",
        ["category_id", "project_id"],
        ["id", "project_id"],
        ondelete="SET NULL",
    )
    op.drop_column("document_type", "category")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "document_type",
        sa.Column("category", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    op.drop_constraint(None, "document_type", type_="foreignkey")
    op.drop_index(op.f("ix_document_type_category_id"), table_name="document_type")
    op.drop_column("document_type", "category_id")
    op.drop_index(
        op.f("ix_template_document_type_template_category_id"),
        table_name="template_document_type",
    )
    op.drop_table("template_document_type")
    op.drop_table("template_category")
    op.drop_index(op.f("ix_category_project_id"), table_name="category")
    op.drop_table("category")
    # ### end Alembic commands ###
