"""auto-generated migration

Revision ID: f3b8af6e7451
Revises: 090bbfca8fb1
Create Date: 2026-01-05 16:46:52.310202

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f3b8af6e7451"
down_revision: str | Sequence[str] | None = "090bbfca8fb1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("document_type", sa.Column("confidence", sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("document_type", "confidence")
    # ### end Alembic commands ###
