"""auto-generated migration

Revision ID: fb1ee44cfcb8
Revises:
Create Date: 2025-12-16 10:49:37.556754

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "fb1ee44cfcb8"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_type",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("category", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_type_project_id"),
        "document_type",
        ["project_id"],
        unique=False,
    )
    op.create_table(
        "document",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=False),
        sa.Column("file_id", sa.UUID(), nullable=False),
        sa.Column("document_type_id", sa.UUID(), nullable=True),
        sa.Column("document_name", sa.String(), nullable=False),
        sa.Column("reasoning", sa.Text(), nullable=True),
        sa.Column("confidence", sa.Float(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["document_type_id"], ["document_type.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_document_document_type_id"),
        "document",
        ["document_type_id"],
        unique=False,
    )
    op.create_index(op.f("ix_document_file_id"), "document", ["file_id"], unique=False)
    op.create_index(
        op.f("ix_document_project_id"), "document", ["project_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_document_project_id"), table_name="document")
    op.drop_index(op.f("ix_document_file_id"), table_name="document")
    op.drop_index(op.f("ix_document_document_type_id"), table_name="document")
    op.drop_table("document")
    op.drop_index(op.f("ix_document_type_project_id"), table_name="document_type")
    op.drop_table("document_type")
    # ### end Alembic commands ###
