apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-workflow
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: spark-workflow
  annotations:
    argocd.argoproj.io/sync-options: Replace=true
    argocd.argoproj.io/manifest-pass-secret-values: "true"
spec:
  source:
    repoURL: https://github.com/RobertinoSolanas/spark-workflow-main.git
    targetRevision: 20dd411e10607fcaf8e655ce21df9a86426820ce
    path: k8s
    kustomize:
      commonLabels:
        app.kubernetes.io/part-of: spark-workflow
        app.kubernetes.io/managed-by: argocd
        deployment-environment: local
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-workflow
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - PrunePropagationPolicy=foreground
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  ignoreDifferences:
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
