apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: spark-workflow
resources:
  - namespace.yaml
  - persistent-volumes.yaml
  - postgresql.yaml
  - elasticsearch.yaml
  - temporal.yaml
  - storage.yaml
  - observability-config.yaml