"""Add REQUIRES_APPROVAL to workflow status

Revision ID: 0bdaa4d270d6
Revises: c2f0f8907dd1
Create Date: 2026-03-06 17:22:28.647021

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0bdaa4d270d6"
down_revision: str | Sequence[str] | None = "c2f0f8907dd1"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


WORKFLOW_STATUS_ENUM_NAME = "workflowstatusenum"


def upgrade() -> None:
    """Upgrade schema."""
    op.execute(
        f"""
        ALTER TYPE {WORKFLOW_STATUS_ENUM_NAME}
        ADD VALUE IF NOT EXISTS 'REQUIRES_APPROVAL';
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
