"""auto-generated migration

Revision ID: 738ae9912ff4
Revises: 45393e06d917
Create Date: 2025-11-19 16:17:11.906095

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "738ae9912ff4"
down_revision: str | Sequence[str] | None = "45393e06d917"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        "CREATE TYPE filetypeenum AS ENUM ('DOCUMENT', 'TEMPLATE', 'LAW_DATA', "
        "'CONTENT_EXTRACTION', 'TEMPORAL_CHECKPOINT')"
    )
    (
        op.add_column(
            "file",
            sa.Column(
                "type",
                sa.Enum(
                    "DOCUMENT",
                    "TEMPLATE",
                    "LAW_DATA",
                    "CONTENT_EXTRACTION",
                    "TEMPORAL_CHECKPOINT",
                    name="filetypeenum",
                ),
                nullable=False,
            ),
        ),
    )
    op.add_column("file", sa.Column("filename", sa.String(), nullable=False))
    op.add_column("file", sa.Column("workflow_id", sa.String(), nullable=True))
    op.add_column("file", sa.Column("run_id", sa.String(), nullable=True))
    op.alter_column("file", "mime_type", existing_type=sa.VARCHAR(), nullable=False)
    op.alter_column("file", "bucket_path", existing_type=sa.VARCHAR(), nullable=False)
    op.create_index(op.f("ix_file_project_id"), "file", ["project_id"], unique=False)
    op.create_index(op.f("ix_file_type"), "file", ["type"], unique=False)
    op.create_index(
        "ix_files_type_project", "file", ["type", "project_id"], unique=False
    )
    op.create_unique_constraint(None, "file", ["bucket_path"])
    op.drop_column("file", "original_file_name")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "file",
        sa.Column(
            "original_file_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
    )
    op.drop_constraint(None, "file", type_="unique")
    op.drop_index("ix_files_type_project", table_name="file")
    op.drop_index(op.f("ix_file_type"), table_name="file")
    op.drop_index(op.f("ix_file_project_id"), table_name="file")
    op.alter_column("file", "bucket_path", existing_type=sa.VARCHAR(), nullable=True)
    op.alter_column("file", "mime_type", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_column("file", "run_id")
    op.drop_column("file", "workflow_id")
    op.drop_column("file", "filename")
    op.drop_column("file", "type")
    # ### end Alembic commands ###
