"""auto-generated migration

Revision ID: 85bd27a6db27
Revises: 9c64a825d7a0
Create Date: 2025-12-08 01:43:27.212331

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "85bd27a6db27"
down_revision: str | Sequence[str] | None = "9c64a825d7a0"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file", sa.Column("deleted", sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file", "deleted")
    # ### end Alembic commands ###
