"""auto-generated migration

Revision ID: 90f1f9a41e38
Revises: 738ae9912ff4
Create Date: 2025-11-21 10:09:59.395323

"""

from collections.abc import Sequence

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "90f1f9a41e38"
down_revision: str | Sequence[str] | None = "738ae9912ff4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("file_bucket_path_key"), "file", type_="unique")
    op.create_index(op.f("ix_file_bucket_path"), "file", ["bucket_path"], unique=True)
    op.create_index(op.f("ix_file_filename"), "file", ["filename"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_file_filename"), table_name="file")
    op.drop_index(op.f("ix_file_bucket_path"), table_name="file")
    op.create_unique_constraint(
        op.f("file_bucket_path_key"),
        "file",
        ["bucket_path"],
        postgresql_nulls_not_distinct=False,
    )
    # ### end Alembic commands ###
