"""auto-generated migration

Revision ID: 9c64a825d7a0
Revises: 90f1f9a41e38
Create Date: 2025-12-04 15:45:53.553496

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "9c64a825d7a0"
down_revision: str | Sequence[str] | None = "90f1f9a41e38"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zip_file",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("filename", sa.String(), nullable=False),
        sa.Column("bucket_path", sa.String(), nullable=False),
        sa.Column("project_id", sa.UUID(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_zip_file_bucket_path"), "zip_file", ["bucket_path"], unique=True
    )
    op.create_index(
        op.f("ix_zip_file_filename"), "zip_file", ["filename"], unique=False
    )
    op.create_index(
        op.f("ix_zip_file_project_id"), "zip_file", ["project_id"], unique=False
    )
    op.add_column("file", sa.Column("source_zip_file_id", sa.UUID(), nullable=True))
    op.create_index(
        op.f("ix_file_source_zip_file_id"), "file", ["source_zip_file_id"], unique=False
    )
    op.create_foreign_key(None, "file", "zip_file", ["source_zip_file_id"], ["id"])
    op.create_unique_constraint(
        "uq_file_zip_entry_source",
        "file",
        ["project_id", "type", "filename", "source_zip_file_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint("uq_file_zip_entry_source", "file", type_="unique")
    op.drop_constraint(None, "file", type_="foreignkey")
    op.drop_index(op.f("ix_file_source_zip_file_id"), table_name="file")
    op.drop_column("file", "source_zip_file_id")
    op.drop_index(op.f("ix_zip_file_project_id"), table_name="zip_file")
    op.drop_index(op.f("ix_zip_file_filename"), table_name="zip_file")
    op.drop_index(op.f("ix_zip_file_bucket_path"), table_name="zip_file")
    op.drop_table("zip_file")
    # ### end Alembic commands ###
