from datetime import date, datetime
from enum import Enum
from uuid import UUID

from pydantic import BaseModel, Field
from pydantic.alias_generators import to_camel


class ProjectStatusEnum(str, Enum):
    """Project status enum values."""

    IN_CREATION = "In Erstellung"
    OPEN = "Offen"
    IN_PROGRESS = "In Bearbeitung"
    APPROVED = "Genehmigt"
    REJECTED = "Abgelehnt"


class ProjectResponse(BaseModel):
    """Pydantic model for Project schema."""

    # Details
    id: UUID
    name: str = Field(..., description="Verfahrensname")
    project_type_id: UUID = Field(..., description="ID of the Verfahren")
    project_type_name: str = Field(..., description="Projekt Type Name")
    created_by_id: UUID | None = Field(
        None, description="ID of the user who created the project"
    )
    entry_date: date = Field(..., description="Antragseingang")
    internal_project_number: str = Field(..., description="Aktenzeichen")

    # Antragsstellenden Details
    salutation: str | None = Field(None, description="Anrede")
    company: str | None = Field(None, description="Firma")
    first_name: str | None = Field(None, description="Vorname Vertretung")
    last_name: str | None = Field(None, description="Nachname Vertretung")
    street: str | None = Field(None, description="Straße")
    house_number: str | None = Field(None, description="Hausnummer")
    address_supplement: str | None = Field(None, description="Adresszusatz")
    plz: str | None = Field(None, description="Postleitzahl")
    location: str | None = Field(None, description="Ort")
    country: str | None = Field(None, description="Land")
    email: str | None = Field(None, description="E-Mail")
    phone: str | None = Field(None, description="Telefon")
    fax: str | None = Field(None, description="Fax")

    # Autogenerated
    status_id: UUID = Field(
        ...,
        description="Status ID of the Verfahren. E.g.: ID of Offen",
    )
    status_name: str = Field(..., description="Status Name")

    current_process_step_id: UUID | None = Field(
        None,
        description="Id of the current process step",
    )

    created_at: datetime = Field(...)
    updated_at: datetime = Field(...)

    model_config = {
        "alias_generator": to_camel,
        "from_attributes": True,
        "populate_by_name": True,
    }


class CreateProjectRequest(BaseModel):
    """Pydantic model for CreateProject schema."""

    # Details
    name: str = Field(..., description="Verfahrensname")
    project_type_id: UUID = Field(..., description="ID of the Verfahren")
    created_by_id: UUID | None = Field(
        None,
        description=(
            "ID of the user who created the project. "
            "Optional for open deployments without built-in authentication."
        ),
    )
    entry_date: date = Field(..., description="Antragseingang")
    internal_project_number: str = Field(..., description="Aktenzeichen")
    status_id: UUID | None = Field(None, description="Projek Status")

    # Antragsstellenden Details
    salutation: str | None = Field(None, description="Anrede")
    company: str | None = Field(None, description="Firma")
    first_name: str | None = Field(None, description="Vorname Vertretung")
    last_name: str | None = Field(None, description="Nachname Vertretung")
    street: str | None = Field(None, description="Straße")
    house_number: str | None = Field(None, description="Hausnummer")
    address_supplement: str | None = Field(None, description="Adresszusatz")
    plz: str | None = Field(None, description="Postleitzahl")
    location: str | None = Field(None, description="Ort")
    country: str | None = Field(None, description="Land")
    email: str | None = Field(None, description="E-Mail")
    phone: str | None = Field(None, description="Telefon")
    fax: str | None = Field(None, description="Fax")

    model_config = {
        "alias_generator": to_camel,
        "populate_by_name": True,
        "json_schema_extra": {
            "examples": [
                {
                    "name": "My Project",
                    "projectTypeId": "00000000-0000-0000-0000-000000000000",
                    "createdById": "00000000-0000-0000-0000-000000000000",
                    "entryDate": "2025-01-01",
                    "internalProjectNumber": "P001",
                    "salutation": "Herr",
                    "company": "Example AG",
                    "firstName": "John",
                    "lastName": "Doe",
                    "street": "Main Street",
                    "houseNumber": "12",
                    "addressSupplement": "Backyard",
                    "plz": "12345",
                    "location": "Berlin",
                    "country": "Germany",
                    "email": "john@example.com",
                    "phone": "1234567890",
                    "fax": "987654321",
                }
            ]
        },
    }


class UpdateProjectRequest(BaseModel):
    """Pydantic model for UpdateProject schema."""

    # Details
    name: str | None = Field(None, description="Verfahrensname")
    project_type_id: UUID | None = Field(None, description="ID of the Verfahren")
    created_by_id: UUID | None = Field(
        None, description="ID of the user who updated the project"
    )
    entry_date: date | None = Field(None)
    internal_project_number: str | None = Field(None)

    # Antragsstellenden Details
    salutation: str | None = Field(None, description="Anrede")
    company: str | None = Field(None, description="Firma")
    first_name: str | None = Field(None, description="Vorname Vertretung")
    last_name: str | None = Field(None, description="Nachname Vertretung")
    street: str | None = Field(None, description="Straße")
    house_number: str | None = Field(None, description="Hausnummer")
    address_supplement: str | None = Field(None, description="Adresszusatz")
    plz: str | None = Field(None, description="Postleitzahl")
    location: str | None = Field(None, description="Ort")
    country: str | None = Field(None, description="Land")
    email: str | None = Field(None, description="E-Mail")
    phone: str | None = Field(None, description="Telefon")
    fax: str | None = Field(None, description="Fax")

    # Metainformation
    status_id: UUID | None = Field(None)
    current_process_step_id: UUID | None = Field(
        None,
        description="Id of the current process step",
    )

    model_config = {
        "alias_generator": to_camel,
        "populate_by_name": True,
        "json_schema_extra": {
            "examples": [
                {
                    "location": "Munich",
                    "company": "Infrastruktur AG",
                }
            ]
        },
    }


class UpdateProjectStatusRequest(BaseModel):
    """Pydantic model for UpdateProjectStatus schema."""

    status_name: str = Field(..., description="Status Name")

    model_config = {
        "alias_generator": to_camel,
        "populate_by_name": True,
        "json_schema_extra": {
            "examples": [
                {
                    "statusName": "Offen",
                }
            ]
        },
    }
