apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-ai-modules
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: spark-workflow
spec:
  project: default
  source:
    repoURL: https://github.com/RobertinoSolanas/spark-workflow-main.git
    targetRevision: 9310d3e
    path: k8s/ai-modules/base
    kustomize:
      namespace: spark-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-workflow
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
