apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spark-backend
  namespace: argocd
  labels:
    app.kubernetes.io/part-of: spark-workflow
spec:
  project: default
  source:
    repoURL: https://github.com/RobertinoSolanas/spark-workflow-main.git
    targetRevision: a3d8757920e92a590a9ec55f2eadb5b202743b79
    path: k8s/backend/base
    kustomize:
      namespace: spark-workflow
  destination:
    server: https://kubernetes.default.svc
    namespace: spark-workflow
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
